config/routes.rb
Rails.application.routes.draw do
  root "posts#index", as: "home"

  get "about" => "pages#about", as: "about"


  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                      length: {minimum: 5}

  validates :body, presence: true,
                      length: {minimum:20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "fortune", password:"123456", only: [:destroy]



  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
   
    # redirect_to post_path(@post)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # def show
  #   @post = Post.find(params[:post_id])
  # end


  # def edit
  #   @post =Comment.find(params[:post_id])
  #   @comment = @post.comment.find(params[:post_id])
  # end

  # def update
    
  #   @post = Comment.find(params[:post_id])
  #   if @comment.update(comment_params)
  #     redirect_to @post
  #   else
  #     render "edit"
  #   end
  # end

  def destroy
    @post =Post.find(params[:post_id])
     @comment = @post.comments.find(params[:id])
     @comment.destroy
      redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = "About us"
    @content = "Welcome to Awesome blog about page. Here you will find everything about us"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with name: "fortune", password:"123456", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
    redirect_to @post
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
     @post.destroy
      redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_form.html.erb
<div class="well fs-5 mx-auto w-50 p-4 mb-4">
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
    <%= f.label :username %><br>
    <%= f.text_field(:username, {:class => "form-control"})%>
</p>
<p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => "form-control"})%>
</p>
<p>
    <%= f.submit({:class => " btn"})%>
</p>
<%end%>
</div>

app/views/comments/_comments.html.erb
<div>
<h1>Comments</h1>
<% @post.comments.each do |comment| %>
<div class=" fs-5 mx-auto w-50 my-4">
<p><strong><%= comment.username%></strong>: <%= comment.body%></p>
 <%= link_to "Delete Comment",[comment.post, comment], 
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                            :class => "text-decoration-none text-danger"%>
</div>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "SimpleBlog", home_path , { :class => "navbar-brand text-info fs-2 font-italic"} %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", home_path , { :class => "css_class text-primary"} %>
        </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li >
          <%= link_to "About", about_path , { :class => "css_class text-primary"} %>
        </li>
        </ul>
        <ul class="nav navbar-nav">
        <li >
          <%= link_to "Create Post", new_post_path, {:style=>'color:black;', :class => "css_class text-primary"} %>
        </li>
        </ul>
      
    </div>
  </div>
</nav>
<%
=begin%>
 <div class="container"> 
<%
=end%>
    <%= yield %>
    <%
=begin%>
 </div> 
<%
=end%>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title%></h1>
<p class="fs-5 mx-auto w-50"><%= @content%></p>

app/views/posts/edit.html.erb
<div class="form">
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
<%= f.label :title,{:class => "label"} %><br>
<%= f.text_field :title, {:class => "input"}  %>
</p>

<p>
<%= f.label :body ,{:class => "label"} %><br>
<%= f.text_area :body, {:class => "form-control", :size => "50x10"} %>
</p>
<p >
<%= f.submit :SubmitPost,{:class => "btn btn-primary"}  %>
</p>
<% end %>
</div>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
<div class="well mb-4 fs-5 mx-auto w-50 p-4">
    <h3 ><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Read More", post_path(post), {:class => "text-decoration-none text-success"}%>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="form">
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
<%= f.label :title,{:class => "label"} %><br>
<%= f.text_field :title, {:class => "input"}  %>
</p>

<p>
<%= f.label :body ,{:class => "label"} %><br>
<%= f.text_area :body, {:class => "form-control", :size => "50x10"} %>
</p>
<p >
<%= f.submit :SubmitPost,{:class => "btn btn-primary"}  %>
</p>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="well m-4 fs-5 mx-auto w-50 p-4">
<h2><%= @post.title%></h2>
<p><%= @post.body%></p>
<hr>
 <%= link_to "Edit Post", edit_post_path(@post), {:class => "text-decoration-none text-success"}%>
 <%= link_to "Delete Post",post_path(@post), 
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                            :class => "text-decoration-none text-danger mx-3"%>
 <%# <%= link_to "Add comment", post_comment_path(@post), {:class => "text-decoration-none text-success"}%> 
</div>

<hr>
<%= render "comments/comments"%>
<%= render "comments/comment_form"%>